info:
  app:
    name: user
    description: User service
  team:
    name: D2 team

spring:
  application:
    name: chat-user-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  api-docs:
    enabled: true
    path: /chat-user-cloud/v3/api-docs

server:
  port: ${PORT:8383}