info:
  app:
    name: user
    description: User service
  team:
    name: D2 team

spring:
  application:
    name: chat-user-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8383}