spring:
  datasource:
    url: ${MESSENGER_DB_URL:jdbc:postgresql://localhost:5435/messenger}
    #url: ${MESSENGER_DB_URL:jdbc:postgresql://chat-postgres:5432/messenger}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    enabled: true
    url: ${MESSENGER_DB_URL:jdbc:postgresql://localhost:5435/messenger}
    #url: ${MESSENGER_DB_URL:jdbc:postgresql://chat-postgres:5432/messenger}
    user: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always