info:
  app:
    name: Messenger
    description: Messenger service
  team:
    name: D2 team

spring:
  application:
    name: chat-messenger-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  api-docs:
    enabled: true
    path: /chat-messenger-cloud/v3/api-docs

server:
  port: ${PORT:8086}