info:
  app:
    name: Subscription
    description: Subscription service
  team:
    name: D2 team

spring:
  application:
    name: chat-subs-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  api-docs:
    enabled: true
    path: /chat-subs-cloud/v3/api-docs

server:
  port: ${PORT:8084}