spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/feed}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/feed}
    user: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always