info:
  app:
    name: Subscription
    description: Subscription service
  team:
    name: D2 team

spring:
  application:
    name: chat-feed-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8381}