spring:
  application:
    name: chat-feed-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
springdoc:
  api-docs:
    enabled: true
    path: /chat-feed-cloud/v3/api-docs
server:
  port: ${PORT:8381}