package file.exception;

public enum ErrorCode {
    INVALID_REQUEST,
    SERVICE_UNAVAILABLE,
    FILE_SERVICE_UNAVAILABLE,
    VALIDATION_FAILED,
    WRONG_FILE,
    FORBIDDEN,
    DOCUMENT_NOT_YOURS,
    UNAVAILABLE_CONTENT_TYPE,
    S3_ERROR
}